"""Models used by the event-driven backtesting framework."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from quant_trader.market_data.models import Bar, OptionContract
from quant_trader.models.common import AssetClass, Side
from quant_trader.strategy.models import PositionTarget


class BacktestFill(BaseModel):
    """Simulated fill generated by the backtest execution model."""

    timestamp: datetime
    instrument_id: str
    side: Side
    quantity: int = Field(gt=0)
    price: float = Field(gt=0)
    slippage: float = Field(ge=0)
    commission: float = Field(ge=0)
    fees: float = Field(ge=0)
    asset_class: AssetClass


class BacktestPosition(BaseModel):
    """Backtest position state."""

    instrument_id: str
    quantity: int
    average_price: float = Field(ge=0)
    asset_class: AssetClass = AssetClass.EQUITY
    contract: OptionContract | None = None


class EquitySnapshot(BaseModel):
    """Point-in-time portfolio equity snapshot."""

    timestamp: datetime
    cash: float
    market_value: float
    equity: float
    realized_pnl: float
    unrealized_pnl: float
    drawdown: float


class PnLAttribution(BaseModel):
    """PnL attribution by instrument and asset class."""

    by_instrument: dict[str, float] = Field(default_factory=dict)
    by_asset_class: dict[str, float] = Field(default_factory=dict)


class BacktestConfig(BaseModel):
    """Backtest runtime configuration."""

    initial_cash: float = Field(default=100_000.0, gt=0)
    benchmark_symbol: str = "SPY"
    allow_fractional_shares: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)


class PendingTarget(BaseModel):
    """Target queued for next-bar execution to avoid lookahead bias."""

    timestamp: datetime
    target: PositionTarget


class BacktestResult(BaseModel):
    """Aggregate backtest outputs."""

    fills: list[BacktestFill]
    equity_curve: list[EquitySnapshot]
    attribution: PnLAttribution
    benchmark_curve: list[tuple[datetime, float]]
    performance_report: dict[str, float | str]
    assumptions: list[str]
    limitations: list[str]


class BarEvent(BaseModel):
    """Internal event wrapper for one bar observation."""

    bar: Bar
